other: add checkout.yaml

diff --git a/.github/workflows/temp/needs.yaml b/.github/workflows/temp/needs.yaml
--- a/.github/workflows/temp/needs.yaml
+++ b/.github/workflows/temp/needs.yaml
@@ -13,17 +13,17 @@ jobs:
     steps:
       - name: echo
         run: echo "job2 done"
-  job3:
-    runs-on: ubuntu-latest
-    steps:
-      - name: echo
-        run: |
-          echo "job3 failed"
-          exit 1
+#  job3:
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: echo
+#        run: |
+#          echo "job3 failed"
+#          exit 1
 #          강제종료
-  job4:
-    runs-on: ubuntu-latest
-    needs: [ job3 ]
-    steps:
-      - name: echo
-        run: echo "job4 done"
+#  job4:
+#    runs-on: ubuntu-latest
+#    needs: [ job3 ]
+#    steps:
+#      - name: echo
+#        run: echo "job4 done"
